= 101 of jQAssistant

http://jqassistant.org/[jQAssistant] helps you to analyse, understand and
keep you software project under control.

To help you to get started with jQAssistant we provide since October 2017
a collection of small tutorials at
https://101.jqassistant.org/startpage/[101.jqassistant.org^]. This
repository contains the sources of there tutorials.

== Contributing

There are several ways to help and contribute:

- Find and fix grammar or spelling issuses and send us a pull request.
- If you miss a topic, please link:./issues/^[create a issue^] for
  the topic we should cover

= Markup Test for jQAssistant 101

[.lead]
Leading section of this article marked `&#91;.lead&#93;`. Li Europan lingues es
membres del sam familie. Lor separat existentie es un myth. Por scientie,
musica, sport etc, litot Europa usa li sam vocabular. Li lingues differe
solmen in li grammatica, li pronunciation e li plu
commun vocabules.

A normal sentence. Li Europan lingues es membres del sam familie.
Lor separat existentie es un myth. Por scientie, musica,
sport etc, litot Europa usa li sam vocabular. Li lingues
differe solmen in li grammatica, li pronunciation e li plu commun vocabules.

== Headline Level I

Li Europan lingues es membres del sam familie.
Lor separat existentie es un myth. Por scientie, musica,
sport etc, litot Europa usa li sam vocabular. Li lingues
differe solmen in li grammatica, li pronunciation e li plu
commun vocabules.

=== Headline Level II

Li Europan lingues es membres del sam familie.
Lor separat existentie es un myth. Por scientie, musica,
sport etc, litot Europa usa li sam vocabular. Li lingues
differe solmen in li grammatica, li pronunciation e li plu
commun vocabules.


==== Headline Level III

Li Europan lingues es membres del sam familie.
Lor separat existentie es un myth. Por scientie, musica,
sport etc, litot Europa usa li sam vocabular. Li lingues
differe solmen in li grammatica, li pronunciation e li plu
commun vocabules.


===== Headline Level IV

Li Europan lingues es membres del sam familie.
Lor separat existentie es un myth. Por scientie, musica,
sport etc, litot Europa usa li sam vocabular. Li lingues
differe solmen in li grammatica, li pronunciation e li plu
commun vocabules.

====== Headline Level V

Li Europan lingues es membres del sam familie.
Lor separat existentie es un myth. Por scientie, musica,
sport etc, litot Europa usa li sam vocabular. Li lingues
differe solmen in li grammatica, li pronunciation e li plu
commun vocabules.


.A title for a XML source listing
[source,xml]
----
<elementA attributeA="value" attributeB="other">
  <nested>value</nested>
</element>
----


.A title for a Java source listing
[source,java]
----
package a.b.c.d;

import java.util.List;

import static java.lang.String.format;

public abstract class Klasse {
    private String name;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;

        return this;
    }
}
----

.Java Source Listing
[source,java]
----
package a.b.c.d;

import java.util.List;

import static java.lang.String.format; // <1>

public abstract class Klasse {
    private String name;               // <2>

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;

        return this;                   // <3>
    }
}
----
<1> Li Europan lingues es membres del sam familie.
<2> Li Europan lingues es membres del sam familie.
<3> Li Europan lingues es membres del sam familie.



TIP: Li Europan lingues es membres del sam familie.
Lor separat existentie es un myth. Por scientie, musica,
sport etc, litot Europa usa li sam vocabular. Li lingues
differe solmen in li grammatica, li pronunciation e li plu
commun vocabules.


IMPORTANT: Li Europan lingues es membres del sam familie.
Lor separat existentie es un myth. Por scientie, musica,
sport etc, litot Europa usa li sam vocabular. Li lingues
differe solmen in li grammatica, li pronunciation e li plu
commun vocabules.


WARNING: Li Europan lingues es membres del sam familie.
Lor separat existentie es un myth. Por scientie, musica,
sport etc, litot Europa usa li sam vocabular. Li lingues
differe solmen in li grammatica, li pronunciation e li plu
commun vocabules.

CAUTION: Li Europan lingues es membres del sam familie.
Lor separat existentie es un myth. Por scientie, musica,
sport etc, litot Europa usa li sam vocabular. Li lingues
differe solmen in li grammatica, li pronunciation e li plu
commun vocabules.
