jqassistant:
  plugins:
    #<1>
    - group-id: org.jqassistant.contrib.plugin
      artifact-id: jqassistant-jmolecules-plugin
      version: 1.4.0

  analyze:
    groups:
      #<2>
      - jmolecules-ddd:Default
      #<3>
      - Default