:imagesdir: includes

= Implementation Of A Scanner Plugin
Dirk Mahler <dirk.mahler@jqassistant.org>

:numbered:

[.lead]
// tag::lead[]
Demonstrates the implementation of a scanner plugin.
// end::lead[]

NOTE: This tutorial is written for version 2.0.6 of jQAssistant.

.Hands On: Implementation Of A Scanner Plugin (German language)
video::577058109[vimeo,width=800,height=450]

== Overview

A scanner plugin allows extending the functionality of jQAssistant to read arbitrary structures (e.g. from
files) and create the corresponding information in the database.
The following example demonstrates this for CSV files using a Maven project.

== Setup Maven Project

The plugin is an artifact which contains the scanner implementation, model classes and a plugin descriptor.
A Maven project needs to declare the following dependencies:

[source,xml]
.pom.xml
----
include::pom.xml[tags=dependencies,indent=0]
----

The following artifacts dependencies are declared:

com.buschmais.jqassistant.core:scanner::
  Provides the scanner plugin API

com.buschmais.jqassistant.plugin:common::
  Contains common functionality shared by plugins,

com.opencsv:opencsv::
  A library http://opencsv.sourceforge.net['opencsv'] for reading CSV files.
  This library is already included in the jQAssistant distribution, therefore the scope is `provided`.

There are also several dependencies defined for implementing tests, see <<Testing>>.

== Define The Graph Model

The model to be stored in the database is defined using the approach provided by http://extended-objects.org[eXtended Objects].
It is based on annotated interfaces declaring methods representing properties and relations.

First a label "CSV" is defined which is going to be used for all nodes created by the scanner:

[source,java]
.CSVDescriptor
----
include::src/main/java/my/project/plugin/scanner/model/CSVDescriptor.java[tags=class]
----

A CSV file is represented by _CSVFileDescriptor_ which inherits from _CSVDescriptor_ and _FileDescriptor_ (provided by the common plugin).
Thus a node of this type will carry the labels "CSV" and "File".
Furthermore a list of "HAS_ROW" relations is defined by the property "rows".

[source,java]
.CSVFileDescriptor
----
include::src/main/java/my/project/plugin/scanner/model/CSVFileDescriptor.java[tags=class]
----

A single row is a node defined by the type _CSVRowDescriptor_ which inherits the label "CSV" from _CSVDescriptor_ and provides
its own label "Row", a property "lineNumber" and a list of "HAS_COLUMN" relations.

[source,java]
.CSVRowDescriptor
----
include::src/main/java/my/project/plugin/scanner/model/CSVRowDescriptor.java[tags=class]
----

_CSVColumnDescriptor_ finally defines a column of a row following the principles explained above:

[source,java]
.CSVColumnDescriptor
----
include::src/main/java/my/project/plugin/scanner/model/CSVColumnDescriptor.java[tags=class]
----

== Implement The Scanner Plugin

The implementation of the plugin itself inherits from _AbstractScannerPlugin_ which requires generic type parameters for the item type it handles and the descriptor type it creates.
In the example _FileResource_ is used which represents a file contained in a directory or archive.
This allows plugins to be independent of the source where files or directories are picked up by the scanner.

The method _accepts_ is called by the scanner to determine if the plugin can handle the given item.
The example matches the value of the parameter path against the file extension ".csv".
The scope parameter may be used to further restrict executions of the plugin, e.g. by checking equality against JavaScope.CLASSPATH.

NOTE: The _accepts_ method must be implemented such that expensive checks (e.g. file access) are completely avoided or only used
after cheap checks (usually by matching file name patterns) have been performed.
Otherwise the overall performance for scanning will decrease notably.

The _scan_ method actually reads the CSV file and stores the gathered data into the database using the interface _Store_ provided by the scanner context.

[source,java]
.CSVFileScannerPlugin
----
include::src/main/java/my/project/plugin/scanner/CSVFileScannerPlugin.java[tags=class]
----

Finally the model and the plugin implementation must be declared in the jQAssistant plugin descriptor:

[source,xml]
./META-INF/jqassistant-plugin.xml
----
include::src/main/resources/META-INF/jqassistant-plugin.xml[]
----

The plugin is automatically loaded by the scanner if it can be found on the classpath, e.g. by adding it as dependency to the Maven plugin.

[[Testing]]
== Add A Test

jQAssistant comes with a test framework which provides convenience functionality for scanning and verifying data.

The CSV scanner plugin shall be tested using the following file:

[source,csv]
.src/test/resources/test.csv
----
include::src/test/resources/test.csv[]
----

.Graph representation of the CSV file
image::graph.svg[Resultset,300,300]

The test class `CSVScannerPluginTest` extends from `AbstractPluginIT` and

- scans the CSV file which is located in the root of the test class path
- executes a Cypher query to lookup the created file node with the labels `CSV` and `Test`
- verifies the created graph representing the CSV structure

[source,java]
.CSVScannerPluginTest
----
include::src/test/java/my/project/plugin/scanner/CSVScannerPluginTest.java[tag=CSVScannerPluginTest]
----

TIP: By default a Neo4j in-memory database is used by the test framework to keep build times short.
During development it is helpful to use a running Neo4j server which provides a browser for exploring the nodes and relations created by the scanner.
Therefore just start the server from the command line using `mvn jqassistant:server` and activate the `@TestStore` annotation.

// TODO naming rules for Labels, properties and relations, probably in manual instead of here

== Resources

1. link:tutorial.zip[ZIP archive including the plugin]
2. link:https://vimeo.com/577058109[Hands On Video on Vimeo (German language)]