= Getting started with jQAssistant, Spring Boot and Maven
Dirk Mahler <dirk.mahler@jqassistant.org>

:numbered:

[.lead]
// tag::lead[]
The tutorial shows the integration of jQAssistant into a https://projects.spring.io/spring-boot/[Spring Boot] application which is built using http://maven.apache.org[Apache Maven].
// end::lead[]

NOTE: This tutorial has been written for jQAssistant 1.4.0

== Prerequisites

- Spring Boot project based on http://maven.apache.org[Maven] as created by https://start.spring.io/[] using the dependencies `Web`, `JPA` and `H2`

== Overview

jQAssistant comes with a plugin for Spring based applications that provides rules for enforcing best practices, e.g.

- allowed dependencies between Controllers, Services and Repositories
- correct usage of transactional methods
- enforcing constructor injection instead of field injection.
- ...

The steps in this tutorial illustrate:

- Integration of the <<MavenPlugin>>
- Working with the <<PreDefinedRules>>
- Definition of <<ProjectSpecificRules>>

[[MavenPlugin]]
== jQAssistant Maven Plugin

jQAssistant runs as part of the build process and therefore needs to be integrated as Maven plugin.
This is done by adding the following setup to the `build/plugins` section of the file `pom.xml`:

.jQAssistant Maven plugin
[source,xml]
----
include::pom.xml[tag=plugin,indent=0]
----

The configuration above

- activates the goals `scan` and `analyze` during a build
- defines the rule group `spring-boot:Strict` to be executed during analysis (alternatively `spring-boot:Default`, for `package:Default` see <<ProjectSpecificRules>>)
- sets severities for printing warnings and breaking the build
- set default severities for concepts that cannot be applied to `INFO`

The Maven build can be triggered as usual using the following command:

----
mvn clean install
----

NOTE: The default severity of concepts is `MINOR` and therefore the default setup would print a warning for each concept that could not be applied,
e.g. if there are @Configuration annotated beans present in the code.
For this reason the proposed configuration sets the default severity to `INFO`.

[[PreDefinedRules]]
== Pre-Defined Rules

The setup above activates the a group `spring-boot:Strict`.

Executing the goal `effective-rules` on the command line using

----
mvn jqassistant:effective-rules
----

prints a summary of the included rules and their description:

----
[INFO] Groups [7]
[INFO]   "spring-boot:Default"
[INFO]   "spring-boot:Strict"
[INFO]   "spring-component:Default"
[INFO]   "spring-component:Strict"
[INFO]   "spring-injection:Default"
[INFO]   "spring-injection:Strict"
[INFO]   "spring-transaction:Default"
[INFO] Constraints [15]
[INFO]   "spring-boot:AllTypesInApplicationPackage" - All types of of a Spring Boot application must be located in the same package or a sub-package of
            the application class.

[INFO]   "spring-component:ControllerMustOnlyDependOnServicesRepositoriesOrComponents" - A Spring controller can only have dependencies to other Spring components that are services or
            repositories.
...
----

[[ProjectSpecificRules]]
== Project Specific Rules

Based on the concepts by the Spring plugin project specific rules may be defined.
These rules must be located in the directory `/jqassistant` and can be written either in
XML or Asciidoc files.

The latter is recommended and used for the following example.
It defines

- a group `package:Default` including the constraint `package:ServicePackage´
- the constraint `package:ServicePackage`that ensures that Spring services

./jqassistant/packages.adoc
....
include::jqassistant/packages.adoc[]
....

Finally the group `package:Default` must be activated, therefore the comment for this group in the file `pom.xml` (see above) must be removed.
