:imagesdir: includes

= Calculate metrics
Jürgen Dufner <juergen [at] jdufner.de>

:numbered:

[.lead]
// tag::lead[]
Describes how to calculate some common metrics.
// end::lead[]

NOTE: This tutorial is written for version 1.6.0 of jQAssistant.

'''

== Introduction

// Why metrics can help you to understand you system?

A famous quote of Peter F. Drucker is

  If you can't measure it, you can't improve it.

////

The quote exists in different variants. I couldn't figure out, what the originally quote is.

  If you can't measure it, you can't manage it.

  If you can't measure it, you can't change it.

  You can't manage what you can't measure.

  If it cannot be measured, it cannot be managed.

////

Metrics are just one way to measure your software system.
They can help you to understand your system and to discover anomalies in your system.
If the anomalies discovered, it's up to you to improve your system to fulfill the metrics.

In the following chapters I describe different metrics and their purpose.
Each chapter consists of following points:

  * Description of the metric.
  * How to calculate the metric with jQAssistant.
  * A simple example how to calculate the metric.

include::jqassistant/ood-metrics.adoc[]

include::jqassistant/visibility-metrics.adoc[]

== Implementation

This metrics are implemented in the https://github.com/jqassistant-contrib/jqassistant-java-metrics-plugin[jQAssistant Java Metrics plugin].

Please check the documentation to apply this metrics in your project.
In cases of issues please report there.

== Critique

I've shown different metrics.
Each of them has a different purpose.
Some focus on coupling, others on visibility or cohesion.
Each can tell you something about your system.

IMPORTANT: Metrics are an indicator, no silver bullet.

The metrics don't know your architectural rules.
Therefore metrics can't express how good your system comply with your architectural rules.
Metrics try to condense information in one or a few numbers, but software architecture is complicate thing and cannot be expressed in just one number.
But metrics a good indicator to describe anomalies regarding to the common understanding of software systems.
They are a hint, that something is rather unusual.
You have to analyse the deviation.

TIP: Define metrics for system, measure them and take a closer look if your expecations aren't met.
Then improve your code or change your metrics' threshold or align your architectural rules.
Repeat this process as long as your system lives.
