:imagesdir: includes

= Sharing Rules Between Projects
Dirk Mahler <dirk.mahler@jqassistant.org>

:numbered:

[.lead]
// tag::lead[]
Define a plugin providing shared rules and use them in different projects.
// end::lead[]

NOTE: This tutorial is written for version 1.4.0 of jQAssistant.

== Overview

jQAssistant allows sharing rules (i.e. concepts, constraints and groups) for being used by different projects.
This is very useful to

- enforce coding standards and guidelines across organizations or teams by providing constraints and concepts
- provide re-usable concepts for widely used frameworks to ease the creation of project specific constraints

Such rules may be shared by distributing them as jQAssistant plugin, this approach is demonstrated in this tutorial.
Two example constraints will be made available:

maven:GroupId::
Verifies that the groupId of all Maven modules follows a specific pattern.

package:RootPackage::
Verifies that all Java classes of a project are located within a specific root package.
As the name of the package is project specific the constraints expects a parameter.

Both rules are embedded in groups for easier execution.

== Providing Rules As Plugin

=== The Plugin Structure

The standard approach of sharing rules is providing them as a jQAssistant plugin.
Therefore a JAR artifact is built using https://maven.apache.org[Apache Maven] with the following `pom.xml`:

[source,xml]
.pom.xml
----
include::rules/pom.xml[indent=0]
----

The folder `src/main/resources/META-INF` contains the plugin descriptor `jqassistant-plugin.xml` declaring the files containing the rules to be shared:

[source,xml]
.src/main/resources/META-INF/jqassistant-plugin.xml
----
include::rules/src/main/resources/META-INF/jqassistant-plugin.xml[]
----

The referenced files are expected as classpath resources in the folder `/META-INF/jqassistant-rules`.
This tutorial uses XML files to declare the rules thus the following folder structure is expected:

[code,raw]
----
/META-INF
        |- jqassistant-plugin.xml
        |- jqassistant-rules
                           |- package.xml
                           |- maven.xml
                           |- my-organization.xml
----


NOTE: Asciidoc files are supported as well but it takes longer time to load them at startup.
Therefore the recommended file format for rules shared within plugins is XML.

The following sections describe the shared rules in detail.

=== Maven Rules

The file `maven.xml` provides rules related to Apache Maven:

[source,xml]
.src/main/resources/META-INF/jqassistant-rules/maven.xml
----
include::rules/src/main/resources/META-INF/jqassistant-rules/maven.xml[]
----

maven:GroupId::
A constraint verifying that each Maven project uses a defined pattern for the `groupId`.

maven:Default::
A group that bundles selected constraints in this XML file for easier execution by just referencing this group.
This approach allows adding or removing rules in the future without the need to change the setup of projects using this plugin.
There might be as well other groups including more or less rules, e.g. `maven:Strict` for more restrictive checks.

=== Package Rules

The file `package.xml` provides rules regarding the package structure:

[source,xml]
.src/main/resources/META-INF/jqassistant-rules/package.xml
----
include::rules/src/main/resources/META-INF/jqassistant-rules/package.xml[]
----

package:RootPackage::
A constraint verifying that all Java types of a project are located within a given root package.
The name of the latter is expected as parameter `rootPackage` which must be present during execution, e.g. by the Maven plugin.

package:Default::
A group with the same purpose as `maven:Default` described above.

Rules may be verified by tests.
The following code snippet shows an example for the constraint `package:RootPackage`:

[source,java]
.src/test/java/my/organization/rules/PackageTest.java
----
include::rules/src/test/java/my/organization/rules/PackageTest.java[tags=Test]
----

=== Grouping All Rules

The file `my-organization.xml` just contains a group:

[source,xml]
.src/main/resources/META-INF/jqassistant-rules/my-organization.xml
----
include::rules/src/main/resources/META-INF/jqassistant-rules/my-organization.xml[]
----

my-organization:Default::
This group bundles the groups `maven:Default` and `package:Default`.
Thus a project using the rules provided by this plugin only needs to declare this group for execution.

TIP: Bundling rules into different groups can be used for staged roll-out into projects.
New constraints at first can be included into a group `my-organization:Staging` and tested by selected projects (e.g. within Maven profiles).
After validation they can be moved to `my-organization:Default` (or groups included there) and thus become mandatory for all projects.

== Using Shared Rules In A Maven Project

This section demonstrates how the set of shared rules may be activated in a Maven based project.
The latter defines its own set of specific rules.
These bundled in the group `project:Default` which is declared in the file `jqassistant/index.adoc`

[source,asciidoc]
.jqassistant/index.adoc
....
include::project/jqassistant/index.adoc[]
....

The Maven build descriptor `pom.xml` contains the declaration for the jQAssistant plugin:

[source,xml]
.pom.xml
----
include::project/pom.xml[tags=plugin,indent=0]
----

- The plugin containing the shared rules is declared as dependency.
- The configuration section selects the groups `my-organization:Default` and `project:Default` for execution.
- Furthermore a value for the parameter `rootPackage` required by the constraint `package:RootPackage` is defined.

The project can now be built as usual and all required rules will be executed:

[source,raw]
----
mvn install
----

== Using Shared Rules With The Command Line Utility

For using shared rules the plugin JAR file must be copied to the folder `plugins/` of the command line utility.

Furthermore a properties file must be created providing rule parameters, i.e. `rootPackage` required by the constraint `package:RootPackage`:

[source,properties]
.ruleParameters.properties
----
rootPackage=my.organization
----

Now the analysis can be executed using the following command:

[source,raw]
----
# Unix
jqassistant.sh analyze -groups my-organization:Default,project:Default -ruleParameters ruleParameters.properties

# Windows
jqassistant.cmd analyze -groups my-organization:Default,project:Default -ruleParameters ruleParameters.properties
----

== Resources

1. link:tutorial.zip[ZIP archive including a Maven example for sharing rules]

